Página do ISOPIN arrumada
rafaeleiki/devy pull request #11
Opened 2017-10-14 20:42 UTC by GuiBrandt

2017-10-14 21:14 UTC, rafaeleiki requested changes
É esperado que todo Pull Request tenha sido pelo menos testado. Houveram erros de compilação.

2017-10-14 21:14 UTC, rafaeleiki commented on src/app/project/2017/isopin.ts
> +  image: 'isopin.png';
Dentro de um JSON, não se usa `;` para terminar um campo, usa-se `,`

2017-10-14 21:14 UTC, rafaeleiki commented on src/app/project/2017/isopin.ts
> +  description: `Sistema de busca e visualização gráfica de interações proteicas entre espécies vegetais que procura diminuir o custo de produção de alimentos transgênicos uma vez que apresenta uma ma
Linha excessivamente longa. Aproveitar que já está usando string multilinha para colocar as quebras de linha corretamente.

2017-10-14 21:14 UTC, rafaeleiki commented on src/app/project/2017/isopin.ts
> +    nationalFairFinalist(['Mostractc 2017']),
Nem `interfacePrototypes` nem `nationalFairFinalist` foram importados.

2017-10-14 23:04 UTC, GuiBrandt commented
Fiz as alterações, perdão pelos problemas com o TypeScript, tivemos alguns problemas aqui para testar (o angular-cli não instala de jeito nenhum). Imagino que agora esteja tudo certo.

2017-10-15 18:33 UTC, rafaeleiki requested changes

2017-10-15 18:33 UTC, rafaeleiki commented on src/app/project/2017/isopin.ts
> +  shortDescription: `Sistema de busca e visualização gráfica de interações
Problema de trailing whitespace. A linha tem que acabar com um caractere diferente de espaço seguido de `\n`. Algumas das linhas do `shortDescription` estão com esse problema.

2017-10-15 21:21 UTC, rafaeleiki approved these changes

2017-10-15 21:21 UTC, merged