Alterações AlphaStudy
rafaeleiki/devy pull request #13
Opened 2017-10-15 23:32 UTC by nathaliajsouza

2017-10-15 23:32 UTC, nathaliajsouza commented
Alterações AlphaStudy

2017-10-16 01:21 UTC, rafaeleiki requested changes

2017-10-16 01:21 UTC, rafaeleiki commented on src/app/project/2017/alpha-study.ts
> + de Campinas, foi realizada uma pesquisa, com formulário
O texto do `shortDescription` possui problemas com trailing whitespace (quando existe um espaço no final da linha antes da quebra de linha - `\n`). Esses espaços precisam ser removidos.

2017-10-19 15:30 UTC, rafaeleiki approved these changes

2017-10-19 15:30 UTC, merged