Updates page for Braille Reader project
rafaeleiki/devy pull request #9
Opened 2017-10-14 00:07 UTC by yohncandido

2017-10-14 21:03 UTC, rafaeleiki requested changes
Poucas alterações e a maior parte delas está dentro do padrão. Fazer alteração solicitada.

2017-10-14 21:03 UTC, rafaeleiki commented on src/app/project/project.component.html
> +  <br />
`<br />` sendo usado para estrutura da página é incorreto.

2017-10-14 21:54 UTC, yohann reviewed
Feita a alteração solicitada.

2017-10-15 18:25 UTC, rafaeleiki approved these changes

2017-10-15 18:25 UTC, merged